# Plombir — a modern, extremely fast static site generator.
#
# Philosophy: Write. Build. Ship.
# Licensed under the Mozilla Public License 2.0 (MPL-2.0).
require "yaml"
require "json"
require "./utils/slug"
require "./content/loader"
require "./content/document"
require "./content/collection"
require "./content/schema"
require "./router/router"
require "./frontmatter/parser"
require "./markdown/renderer"
require "./template/error"
require "./template/lexer"
require "./template/ast"
require "./template/parser"
require "./template/engine_v0"
require "./renderer/page"
require "./assets/fingerprint"
require "./assets/manifest"
require "./assets/pipeline"
require "./assets/rewrite"
require "./build/pipeline"
require "./build/incremental"
require "./server/server"
require "./livereload/reload"
require "./watcher/watcher"
require "./doctor/doctor"
require "./config/config"
require "./config/permalink"
require "./check/issue"
require "./check/content"
require "./check/routes"
require "./check/html"
require "./check/links"
require "./check/assets"
require "./check/seo"
require "./check/runner"
require "./scaffold/templates"
require "./scaffold/site"
require "./cli/base"
require "./cli/build"
require "./cli/serve"
require "./cli/dev"
require "./cli/preview"
require "./cli/clean"
require "./cli/doctor"
require "./cli/check"
require "./cli/version"
require "./cli/help"
require "./cli/new"

module Plombir
  VERSION = "0.1.0"
end
