# Plombir — a modern, extremely fast static site generator.
#
# Philosophy: Write. Build. Ship.
# Licensed under the Mozilla Public License 2.0 (MPL-2.0).
require "yaml"
require "json"
require "./utils/slug"
require "./utils/html"
require "./content/loader"
require "./content/document"
require "./content/collection"
require "./content/pagination"
require "./content/taxonomy"
require "./content/data"
require "./content/schema"
require "./router/router"
require "./frontmatter/parser"
require "./markdown/renderer"
require "./template/error"
require "./template/lexer"
require "./template/ast"
require "./template/parser"
require "./template/engine_v0"
require "./renderer/page"
require "./seo/head"
require "./seo/sitemap"
require "./seo/robots"
require "./feeds/rss"
require "./search/index"
require "./assets/fingerprint"
require "./assets/manifest"
require "./assets/pipeline"
require "./assets/rewrite"
require "./build/pipeline"
require "./build/incremental"
require "./server/server"
require "./livereload/reload"
require "./watcher/watcher"
require "./doctor/doctor"
require "./config/config"
require "./config/permalink"
require "./check/issue"
require "./check/content"
require "./check/routes"
require "./check/html"
require "./check/links"
require "./check/assets"
require "./check/seo"
require "./check/search"
require "./check/runner"
require "./scaffold/templates"
require "./scaffold/site"
require "./import/jekyll"
require "./cli/base"
require "./cli/build"
require "./cli/serve"
require "./cli/dev"
require "./cli/preview"
require "./cli/clean"
require "./cli/doctor"
require "./cli/check"
require "./cli/import"
require "./cli/version"
require "./cli/help"
require "./cli/new"

module Plombir
  VERSION = "1.0.0"

  # Short git SHA baked in at compile time (`--version` reports it);
  # "unknown" when built outside a git checkout (e.g. source tarball).
  COMMIT = {{ `git rev-parse --short HEAD 2>/dev/null || echo unknown`.stringify }}.chomp
end
